version: '3.9'
services:
  test_ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server-1
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=test #optional
      - USER_NAME=test #optional
    ports:
      - 2222:2222
    restart: unless-stopped

  test_ssh2:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server-2
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=test #optional
      - USER_NAME=test #optional
    ports:
      - 2333:2222
    restart: unless-stopped
